name: Manual Maven Build via Jump Host

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      
      environment:
        description: 'Environment'
        required: true
        default: 'prod'
        type: choice
        options:
        - dev
        - stage
        - prod
env:
  # Dynamic variables based on environment selection
  REPOSITORY: moizbigdata/ec2-ubuntu22.04-build-machine
  AWS_REGION: us-east-1
jobs:
  Manual_Maven_Build:
     # if: ${{ !inputs.skip_job }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
  
      - name: Checkout main 
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          ls -la
          cd spring-petclinic && mvn clean package
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "spring-petclinic/target"
          REMOTE_HOST: ${{ secrets.JUMP_HOST_IP }}
          REMOTE_USER: ${{ secrets.JUMP_HOST_USER }}
          SCRIPT_BEFORE: |
            whoami
            ls -al

   
      